### ISSUE TITLE
How to run your package in Google Colab?

### ISSUE THREAD

**Issue by ssqd2022** [DidierRLopes/fear-greed-index#1]
Dear Developer:

Through internet search, I found your cool package in Python.  I wonder how to install it within Google CoLab online environment?
Of course, I will try to download the codes into a local computer and run from there. 

Thank you so much for this wonderful project!

ssqd2020

**Comment by DidierRLopes** [comment]
Hey @ssqd2022,

Sorry for delay on this response. I had not use Google colab before, so confirm that you are happy with what I added - I will close this ticket with the assumption you are. Feel free to re-open if you are not happy!

Notebook [here](https://github.com/DidierRLopes/fear-greed-index/blob/main/feargreed_index.ipynb) and Colab [here](https://colab.research.google.com/github/DidierRLopes/fear-greed-index/blob/main/feargreed_index.ipynb).

The format of the fear-greed-index package may not be the best, but note that this was to accommodate it for the [GamestonkTerminal](https://github.com/GamestonkTerminal/GamestonkTerminal).

Have a great week! 😄

**Comment by ssqd2022** [comment]
Thank you so much for your help!!!

Another question. What if I want to check the CNN fear and greedy index value every 5 minutes from 9:30 am -4:30 pm.  Can you provide a stream IO so that we can do that?

**Comment by DidierRLopes** [comment]
> Thank you so much for your help!!!
> 
> Another question. What if I want to check the CNN fear and greedy index value every 5 minutes from 9:30 am -4:30 pm. Can you provide a stream IO so that we can do that?

The package scraps information from here: https://money.cnn.com/data/fear-and-greed/

And from the updated dates in there, it seems that it's not updated that regularly! So for your use case I don't think it will be necessary :)
